# Generated by Django 5.0.4 on 2024-05-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Submissions",
            new_name="Submission",
        ),
    ]
