# Generated by Django 5.0.4 on 2024-05-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_rename_submissions_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
